### ISSUE TITLE
Domain and script updates

### ISSUE THREAD

**Issue by Aldroc** [SAM10795/AnistreamIN#3]
A few suggestions, first the github hosting makes the site a bit difficult to access if you don't have the exact link itself. The URL is too convoluted. Hosting on Netlify takes care of that, as you could assign a more easily memorable and simple URL for the website for free, also it automatically updates the site whenever a new commit is made so there is that.

Also both new - old and old - new sorting does not work. Do look into that

**Comment by SAM10795** [comment]
I'll look into Netlify migration soon
Old-New and New-Old is dependent on when the data was added to the platform/this website. For most, the default is 27/5 which is why the update sorting might appear to be not working. New-Old should be working for most websites though because data has been updated regularly since the first commit

**Comment by Aldroc** [comment]
> For most, the default is 27/5 which is why the update sorting might appear to be not working. New-Old should be working for most websites though because data has been updated regularly since the first commit

Ohh ok I thought it was supposed to be their air dates. oops :P
